# -*- coding: utf-8 -*-
"""Prak Algo 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_AnU88yOV49vzBQjsouDzexJeckcOsX
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def decimal_to_binary(decimal):
    binary = bin(decimal)
    return binary[2:]  # Menghilangkan awalan '0b' pada hasil biner

def binary_to_decimal(binary):
    decimal = int(binary, 2)
    return decimal

while True:
    print("----PROGRAM KONVERSI BILANGAN----")
    print("Pilih operasi:")
    print("1 -> Angka ke Biner")
    print("2 -> Biner ke Angka")
    print("3 -> Exit")

    choice = input("Masukkan pilihan Anda : ")

    if choice == '1':
        decimal_input = int(input("Masukkan bilangan desimal: "))
        binary_output = decimal_to_binary(decimal_input)
        print(f"Hasil konversi: {binary_output}")
    elif choice == '2':
        binary_input = input("Masukkan bilangan biner: ")
        decimal_output = binary_to_decimal(binary_input)
        print(f"Hasil konversi: {decimal_output}")
    elif choice == '3':
        print("Terima kasih!!!!")
        break
    else:
        print("Pilihan tidak valid. Silakan pilih 1, 2, atau 3.")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def cek_angka_genap(lst):
    for angka in lst:
        if angka % 2 == 0:
            return True
    return False

input_str = input("Masukkan list angka (integer)-> ")
angka_list = [int(x) for x in input_str.split()]

hasil = cek_angka_genap(angka_list)

if hasil:
    print("List memiliki angka genap.")
else:
    print("List tidak memiliki angka genap.")